version: '3.9'

services:
  percona-xtrabackup:
    build: .
    env_file:
      - .env
    volumes:
      - xbackup_volume:/xbackup
      - /var/lib/mysql:/var/lib/mysql
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
    network_mode: host

    restart: on-failure


volumes:
  xbackup_volume:
    external: true
    name: ${XBACKUP_VOLUME}

