version: '3.9'

services:
  percona-xtrabackup:
    build: .
    env_file:
      - .env
    volumes:
      - ${XBACKUP_VOLUME}:/xbackup
      - ${DB_DATA_DIR}:${DB_DATA_DIR}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: on-failure

