version: '3.9'

services:
  percona-xtrabackup:
    build: .
    env_file:
      - .env
    volumes:
      - ${XBACKUP_VOLUME}:/xbackup
      - ${DB_DATA_DIR}:${DB_DATA_DIR}
    network_mode: host
    restart: on-failure

